# Optimization Methods: Assignment 1

## Part 1: exercise

### **1. What is the definition of a symmetric matrix?**



A **symmetric matrix** is a square matrix that is equal to its **transpose**. Formally, a matrix $A$ is symmetric if:

$$
A = A^T
$$

### **2. What are the definitions of eigenvalues and eigenvectors?**

Let $V$ be a vector space over a field $K$ (for example, $\mathbb{R}$, the field of real numbers), and let the linear application $f: V \to V$ be an **endomorphism**. 

We say that a vector $v \in V$ is an **eigenvector**, and $\lambda$ is its **eigenvalue**, if:

$$
f(v) = \lambda v
$$

In other words, the linear transformation **does not change the direction** of $v$, but only **scales** it by a factor of $\lambda$.

In the case of a **matrix** $A$, a vector $v$ is an eigenvector, and $\lambda$ is its eigenvalue if:

$$
Av = \lambda v
$$

This means that applying the transformation $A$ to $v$ is the same as scaling $v$ by $\lambda$.

Most vectors change direction when a transformation (such as rotation or stretching) is applied. However, **eigenvectors** are "special" because they only get stay stretched, squished or flipped but they always stay on the same line, without changing direction.

A matrix may have multiple eigenvectors with different eigenvalues. If we find a complete set of eigenvectors that span the space, they form an **eigenbasis**.

### **3. What is a singular matrix?**

A **singular matrix** is a square matrix that **doesn't have an inverse**. This occurs when the determinant of the matrix is zero. Formally, a matrix $A$ is **singular** if:

$$
\det(A) = 0
$$

In fact, a singular matrix has **linearly dependent** rows or columns. This means that at least one row or column can be written as a linear combination of others. Consequently, The **rank** of a singular matrix is less than its size. A singular matrix always has at least one **eigenvalue** equal to zero.


### **4. What is the definition of a positive definite matrix? definition of a positive semi-definite matrix?**

A **square matrix** $A$ is **positive definite** if, for every non-zero vector $x \in \mathbb{R}^n$, it’s true that:

$$
x^T A x > 0
$$

In particular, a positive definite matrix is always **symmetric**, which means $A = A^T$, but the opposite is not guaranteed. Furthermore, in a positive definite matrix, all eigenvalues of $A$ are strictly positive ($\lambda_i > 0$), and the determinants of all sub-matrices obtained by eliminating successive rows and columns are positive.

### Example:

I will use an example I created in the Numerical Computing course. Let’s verify if the following matrix is positive definite:

$$
A =
\begin{bmatrix}
2 & -1 \\
-1 & 2
\end{bmatrix}
$$

We will use a generic vector $x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}$.

We want to compute:

$$
x^T A x = 
\begin{bmatrix} x_1 & x_2 \end{bmatrix}
\begin{bmatrix} 2 & -1 \\ -1 & 2 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
$$

We first compute $A x$:

$$
A x =
\begin{bmatrix}
2 & -1 \\
-1 & 2
\end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
=
\begin{bmatrix}
2x_1 - x_2 \\
-x_1 + 2x_2
\end{bmatrix}
$$

Now, we compute $x^T A x$:

$$
x^T A x = 
\begin{bmatrix} x_1 & x_2 \end{bmatrix}
\begin{bmatrix}
2x_1 - x_2 \\
-x_1 + 2x_2
\end{bmatrix}
$$

$$
x^T A x = x_1(2x_1 - x_2) + x_2(-x_1 + 2x_2)
$$


$$
x^T A x = 2x_1^2 - x_1 x_2 - x_1 x_2 + 2x_2^2
$$

$$
x^T A x = 2x_1^2 - 2x_1 x_2 + 2x_2^2
$$

This can be rewritten as:

$$
x^T A x = (x_1 - x_2)^2 + x_1^2 + x_2^2
$$

Since $(x_1 - x_2)^2$, $x_1^2$, and $x_2^2$ are all non-negative, and their sum is strictly positive for any nonzero vector $x$, we conclude that the matrix $A$ is **positive definite**.

Similarly, A **positive semi-definite matrix** is a symmetric matrix $A$ that satisfies the following condition for all vectors $x \in \mathbb{R}^n$:

$$
x^T A x \geq 0
$$


### **5. Let $M \in \mathbb{R}^{n \times n}$ a nonsingular square matrix and let $A = M^T M$. Prove that $A$ is positive definite. Hint: Recall that $x^T x = \|x\|^2$ for $x \in \mathbb{R}^n$.**

To prove that $A = M^T M$ is positive definite, we need to show that for every non-zero vector $x \in \mathbb{R}^n$:

$$
x^T A x > 0
$$

Since

$$
A = M^T M
$$

We consider the expression $x^T A x$ as:

$$
x^T A x = x^T (M^T M) x
$$

And we can rewrite this expression as:

$$
x^T (M^T M) x = (Mx)^T (Mx)
$$

The term $(Mx)^T (Mx)$ is the dot product of the vector $Mx$ with itself, which is the square of the Euclidean norm of the vector $Mx$:

$$
(Mx)^T (Mx) = \|Mx\|^2
$$

So, we have:

$$
x^T A x = \|Mx\|^2
$$

Since $M$ is nonsingular (invertible), then there is no non-zero vector $x$ such that $M x = 0$ and:

$$
\|Mx\|^2 > 0
$$

So, for any non-zero $x \in \mathbb{R}^n$:

$$
x^T A x = \|Mx\|^2 > 0
$$

We can conclude that, since $x^T A x > 0$ for all non-zero vectors $x \in \mathbb{R}^n$, $A = M^T M$ is **positive definite**.

## Part 2: programming problem

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx

### **1. Create a vector b with the elements:**

$$
b = \begin{bmatrix}
-3 \\
-8 \\
7
\end{bmatrix}
$$

In [2]:
# Create vector B
b = np.array([-3, -8, 7])
print(b)

[-3 -8  7]


### **2. Create and print the matrix $A$ with the elements:**

$$
A = \begin{bmatrix}
-10 & 3 & 11 \\
3 & -5 & -4 \\
11 & -4 & -7
\end{bmatrix}
$$

In [3]:
# Create matrix A
A = np.array([[-10, 3, 11],
              [3, -5, -4],
              [11, -4, -7]])

print(A)

[[-10   3  11]
 [  3  -5  -4]
 [ 11  -4  -7]]


### **3. Is the matrix $A$ symmetric? Write your answer in a cell in the notebook and then check it with Python.**

Yes the matrix $A$ is symmetric, and to show that we can easily check that the matrix $A$ is symmetric by comparing it to its transpose.

In [33]:
# Check if the matrix A is symmetric, meaning if it's equal to its transpose
symmetric = np.array_equal(A, A.T)

if symmetric:
    print("The matrix A is symmetric.")
else:
    print("The matrix A is not symmetric.")

The matrix A is symmetric.


### **4. Compute $x$ as the solution of the linear system $A x = b$ and print it.**

In [4]:
print("The vector b is:", b)

# Solve for x in the equation Ax = b
x = np.linalg.solve(A, b)
print("The solution vector x is:", x)

The vector b is: [-3 -8  7]
The solution vector x is: [2. 2. 1.]


### **5. To check if the solution is correct, compute $r$ as the product $A x$ and print it.**

In [5]:
# Compute the residual r = Ax to check if the solution is correct (the values should match the values of vector b)
r = np.dot(A, x)
print("The residual r = Ax is:", r)

The residual r = Ax is: [-3. -8.  7.]


### **6. Print the difference of $r$ and $b$ as $||r−b||$. (This should be zero. Is it? Briefly discuss this in the cell for this question.)**

In [7]:
# Compute the difference r - b
diff = r - b

# Compute the Euclidean norm of the difference ||r - b||
norm_diff = np.linalg.norm(diff)

print("Difference (r - b):", diff)
print("Euclidean norm of (r - b):", norm_diff)

tolerance = 1e-10
if norm_diff < tolerance:
    print("The solution is correct (approximately zero).")
else:
    print("The solution is not correct because has a non-zero residual.")

Difference (r - b): [ 1.77635684e-15  8.88178420e-16 -1.77635684e-15]
Euclidean norm of (r - b): 2.6645352591003757e-15
The solution is correct (approximately zero).


We want the Euclidean norm $||r - b||$ to be 0 because it represents the residual error between the result $r$ (calculated as $A x$) and the vector $b$ (the expected result). If the norm is 0, it means that our solution $x$ perfectly satisfies the equation $A x = b$ with no errors.

However, when solving a system of linear equations using $np.linalg.solve(A, b)$, the computed solution $x$ is represented in floating-point format. When we work with floating-point numbers in computers, we often have some small rounding errors. This happens because many numbers cannot be represented exactly in binary form. This limitation, like in this case, is the main reason why floating-point calculations can sometimes give results that are very close to the correct value, but not exactly the same. For instance, the result we just got is a very small number, and it is essentially zero, but we still get a small error. When we work with floating-point numbers we often treat very small numbers as zero, usually setting a small threshold.

### **7. Print the determinant of $A$.**

In [8]:
# Calculate the determinant of A
det_A = np.linalg.det(A)
print("The determinant of A is:", det_A)

The determinant of A is: 214.0000000000001


### **8. Repeat questions 2-7 for the matrix $A1$ with the elements:**

$$
A = \begin{bmatrix}
-1 & 3000 & 1 \\
2000 & -1.5 & -2.5 \\
-1999 & -2998.5 & 1.5
\end{bmatrix}
$$

Even though it's not a good thing to duplicate the code, in order to show everything clearly I will copy the code in the box below to show the results for this new matrix:

In [ ]:
# 2
A1 = np.array([[-1, 3000, 1],
              [2000, -1.5, -2.5],
              [-1999, -2998.5, 1.5]])

np.set_printoptions(precision=4, suppress=True)
print(A1)

# 3
symmetric = np.array_equal(A1, A1.T)

if symmetric:
    print("The matrix A is symmetric.")
else:
    print("The matrix A is not symmetric.")

# 4
x1 = np.linalg.solve(A1, b)
print("The vector b is:", b)
print("The solution vector x is:", x1)

# 5
r1 = np.dot(A1, x1)
print("The residual r = Ax is:", r1)

# 6
diff1 = r1 - b
norm_diff1 = np.linalg.norm(diff1)
print("Difference (r - b):", diff1)
print("Euclidean norm of (r - b):", norm_diff1)

tolerance = 1e-10
if norm_diff1 < tolerance:
    print("The solution is correct (approximately zero).")
else:
    print("The solution is not correct because has a non-zero residual.")
    
# 7
det_A1 = np.linalg.det(A1)
print("The determinant of A is:", det_A1)

# Condition number
cond_A1 = np.linalg.cond(A1)
print("Condition number of A1:", cond_A1)

[[   -1.   3000.      1. ]
 [ 2000.     -1.5    -2.5]
 [-1999.  -2998.5     1.5]]
The matrix A is not symmetric.
The vector b is: [-3 -8  7]
The solution vector x is: [ 2.2514e+13 -5.9973e+12  1.8014e+16]
The residual r = Ax is: [-8. -8. 16.]
Difference (r - b): [-5.  0.  9.]
Euclidean norm of (r - b): 10.295630140987
The solution is not correct because has a non-zero residual.
The determinant of A is: 6.6613364824164e-10
Condition number of A1: 2.857550790184196e+18


The results are reported below:

2. I created the matrix $A1$

3. The matrix $A1$ is not symmetric

4. With the vector $b$ = [-3, -8, 7] the solution vector $x$ is: [2.2514e+13, -5.9973e+12, 1.8014e+16]

5. The residual $r = A x$ is: [-8, -8, 16]

6. The Difference $r - b$ = [-5, 0, 9] and the Euclidean norm is 10.295630140987, meaning the solution has a non-zero residual so it's not accurate.

7. The determinant of matrix $A1$ is: 6.6613364824164e-10

The results for this matrix $A_1$ are "weird" but they can be explained by considering the numerical instability given bt the high condition number and the determinant of the matrix really close to 0.

First of all, as we said, the residual vector $r - b$ ideally should be close to zero, indicating that the computed solution accurately satisfies $A x = b$.

However, in this case, the Euclidean norm of the residual $\|r - b\| \approx 10.2956$ is relatively large, suggesting that we encountered some numerical unprecisions.

In fact, the solution vector contains values on the order of $10^{12}$ to $10^{16}$, which can lead to numerical instability. In particular, extremely large solution values typically occur when the matrix $A_1$ is nearly singular or ill-conditioned.

We notice that the determinant of $A_1$ is extremely small: $\text{det}(A_1) \approx 6.66 \times 10^{-10}$ and, like we saw in part 1, a determinant very close to zero implies that the matrix is nearly singular, making it numerically difficult to solve the system $A x = b$.

However, in this case the main problem is given by the fact that the matrix is ill-conditioned. Since the condition number is given by the difference of the largest eigenvalue for the smallest eigenvalue, a condition number of $2.85 \times 10^{18}$ means that the largest eigenvalue is much bigger than the smallest eigenvalue, confirming that the matrix is nearly singular. All this means that even small changes in $b$ or small floating point numbers errors in rounding can significantly impact the solution $x$, leading to numerical instability. This basically makes $np.linalg.solve(A1,b)$ unreliable for this case. Maybe, we should instead choose another method more efficient for this kind of matrices, for example using the Singular Value Decomposition (SVD) for a more stable solution.

In [38]:
print("Optimization Methods SP25 - Assignment 1")
print("Lorenzo Galli - Università della Svizzera Italiana (USI)")

Optimization Methods SP25 - Assignment 1
Lorenzo Galli - Università della Svizzera Italiana (USI)
